### ISSUE TITLE
Support TypeScript

### ISSUE THREAD

**Issue by innocenzi** [vbenjs/vite-plugin-svg-icons#22]
Hey,

So I'd like to have auto-completion on my icon names. A simple solution for that would be to generate a declaration file like `icons.d.ts` with a simple type: 

```ts
declare type SvgIcon = 'users' | 'menu-alt' | 'home' | 'library' // ...
```

And using it in a component: 

```vue
<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<{ name: SvgIcon }>() // <-- here
const symbolId = computed(() => `#icon:${props.name.includes(':') ? props.name : `:${props.name}`}`)
</script>

<template>
	<svg aria-hidden="true">
		<use :href="symbolId" />
	</svg>
</template>
```

![](https://i.imgur.com/CNGV4L1.png)

This approach is taken from some plugin in the ecosystem, like `antfu/vite-plugin-components` which generates a `components.d.ts`. 

I couldn't find how to use `import ids from 'virtual:svg-icons-names'` in a plugin to do this myself, so I see no other way than a first-party support.

**Comment by gnuletik** [comment]
Hi !
Thanks for implementing this !

However, I can't find a way to use it.
```ts
import ids from 'virtual:svg-icons-names'

typeof ids // type is string[]
typeof ids[number] // type is string

type IconName = typeof ids[number]

// logs: 'users', 'menu-alt'
console.log(ids)

// should throw a typescript error
const someIcon: IconName = 'icon-does-not-exist'
```

In order to let Typescript infer type from values, it seems that the export should be
```ts
export default ['users', 'menu-alt'] as const
```
cf https://steveholgado.com/typescript-types-from-arrays/

However, it doesn't seems defined as const 
https://github.com/vbenjs/vite-plugin-svg-icons/blob/d4d719ec1e465cd69b9153439f23d94aed94ab58/packages/core/src/index.ts#L152

Could you add `as const` to the export ?

Thanks!

**Comment by gnuletik** [comment]
I also tried to create a plugin that would generate a virtual import to export `['icon-name', ...] as const` but I'm unable to use `import ids from 'virtual:svg-icons-names'` from a vite plugin as stated by @innocenzi.

For now, I'm manually handling the type of IconNames.

Thanks!

**Comment by unstoppablecarl** [comment]
how can I disable the generation of `components.d.ts` file?
