### ISSUE TITLE
virtual:svg-icons-names 的使用有例子吗, 我这边引入报错很奇怪

### ISSUE THREAD

**Issue by opcooc** [vbenjs/vite-plugin-svg-icons#23]
![image](https://user-images.githubusercontent.com/34977303/136691481-900cdf72-263f-435c-93df-fd4ff7f3183c.png)

**Comment by DarknessChaser** [comment]
![image](https://user-images.githubusercontent.com/22089140/142817660-c8644584-1fa4-403f-9a3e-cfc2b31bbb99.png)
遇到类似的问题

**Comment by DarknessChaser** [comment]
暂时用 // @ts-ignore 解决了

**Comment by anncwb** [comment]
see 
- https://github.com/vbenjs/vite-plugin-svg-icons/blob/0d69d7e2cb134249999f2745beefd56b0a67aeaf/packages/playground/basic/src/main.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L6
- https://github.com/vbenjs/vite-plugin-svg-icons#typescript-support
