### ISSUE TITLE
manualChunks generates different files

### ISSUE THREAD

**Issue by Ti-webdev** [vbenjs/vite-plugin-svg-icons#24]
For each build sprite is different.

vite.config.js
```
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (id.startsWith('virtual:svg-icons-')) {
            return 'sprite';
          }
```

The reason is:
`SVG_DOM_ID = '__svg__icons__dom__' + new Date().getTime()`

I think it shoudn't be date based on build time.

**Comment by imShara** [comment]
I think it should not be dynamic at all, or passed with `viteSvgIcons({ domId: 'custom' })`

**Comment by danimalweb** [comment]
It would be great to be able to be specific with a custom id name.

**Comment by anncwb** [comment]
2.0.0 already supported
