### ISSUE TITLE
怎么修改svg的颜色呢？

### ISSUE THREAD

**Issue by ILfengzi** [vbenjs/vite-plugin-svg-icons#28]
请问怎么修改svg的颜色呢？传入color值并不起作用

**Comment by leaderli** [comment]
一些svg文件的stroke是写死的，将其更改为currentColor即可。等作者合并 #32

**Comment by ILfengzi** [comment]
好像还有fill属性值，有些也是写死的，是不是也要改一下fill？

**Comment by leaderli** [comment]
看你是否需要了呗，stroke就能改图标颜色了，fill应该是背景色吧

**Comment by ILfengzi** [comment]
这个修改会导致[#66](https://github.com/vbenjs/vite-plugin-svg-icons/issues/66)的问题，这应该是图标本身的问题，可以由图标使用者改，而不是在源码内强制修改，所以建议撤回这个合并 @leaderli @anncwb
