### ISSUE TITLE
version 1.1.0 changelog

### ISSUE THREAD

**Issue by gnuletik** [vbenjs/vite-plugin-svg-icons#37]
Hi,
A new release (v1.1.0) was published on NPM 4 days ago.

However, this repository has no commits for one month.
What the release v1.1.0 contains ? Can you update the CHANGELOG.md?

Thanks!

**Comment by renestalder** [comment]
I quickly checked the code of the published npm package to ensure there is no malicious changes in it. It looks like the changes are most of all related to dependency updates and ESM handling.

One interesting “feature” I see in the diff is the ability to replace stroke colours in SVG with `currentColor`.

@anncwb Could you enlighten us about the recent changes that are not on GitHub but were published to npm? Seems like someone forgot to git push.

**Comment by anncwb** [comment]
2.0.0 has been pushed
