### ISSUE TITLE
the content obtained by parsing the wrong svg file is undefined, can be considered for optimization, thks!

### ISSUE THREAD

**Issue by hxrui** [vbenjs/vite-plugin-svg-icons#38]
- Vesion: 1.1.0

- Problem Description ： The content obtained by parsing the wrong svg file is undefined, and continue to execute downward to report an error.

- Error Screenshot

![image-20220108124300440](https://gitee.com/haoxr/image/raw/master/default/image-20220108124300440.png)

**Comment by BonjourHan** [comment]
I have the same problem
