### ISSUE TITLE
how to use this plugin in libary mode of vite

### ISSUE THREAD

**Issue by carmel** [vbenjs/vite-plugin-svg-icons#39]
I guess it's because of the `import 'virtual:svg-icons-register'` line of code in `main.js`, which is the entrance of vue project, the component library built under vite's library mode doesn't display the svg icon properly. Maybe it's because I didn't import `vite-plugin-svg-icons` in the new project, but I don't want to import it either, because the library component shouldn't be a separate library?

Does anyone have a solution? Thanks in advance!

**Comment by casyalex** [comment]
I met this situation too... And my main project use the same plugin too archive svg icon, and it broke the main project @carmel do you find any solutions?

**Comment by arthrfrts** [comment]
I am on the same boat. @carmel, how did you provide your sprite through the library mode?
