### ISSUE TITLE
 Can't traverse iconDirs recursively

### ISSUE THREAD

**Issue by FaDeAway666** [vbenjs/vite-plugin-svg-icons#40]
My iconDirs is `[path.resolve(__dirname, 'src/assets/svgs')]`
I can get icon like this
![capture_20220124000053168](https://user-images.githubusercontent.com/28639704/150687223-34f13833-c4aa-4202-8a73-f8ef47792428.png)
but if there are sub directories in folder `src/assets/svgs`, I can't get icon
![capture_20220124000129485](https://user-images.githubusercontent.com/28639704/150687311-dc4d5df8-4782-4433-bf77-124b70d7e148.png)

**Comment by FaDeAway666** [comment]
能不能支持一下根路径递归，不要传递path数组呢

**Comment by anncwb** [comment]
You can set symbolId: 'icon-[name]', or `icon-svgs-user-bi-add-app`
