### ISSUE TITLE
安装vite-plugin-svg-icons时依赖冲突  想运行vue-vben-admin框架时

### ISSUE THREAD

**Issue by flyrun9527** [vbenjs/vite-plugin-svg-icons#41]
![image](https://user-images.githubusercontent.com/66985784/151479869-89d15d3d-a40f-4a9b-a518-44e74f7973e7.png)

我一个个测试 在安装vite-plugin-svg-icons时报错

依赖如下
  "dependencies": {
    "@ant-design/colors": "^6.0.0",
    "@ant-design/icons-vue": "^6.0.1",
    "@iconify/iconify": "^2.1.1",
    "@logicflow/core": "^1.0.7",
    "@logicflow/extension": "^1.0.7",
    "@vue/runtime-core": "^3.2.29",
    "@vue/shared": "^3.2.29",
    "@vueuse/core": "^7.5.4",
    "@vueuse/shared": "^7.5.4",
    "@zxcvbn-ts/core": "^1.2.0",
    "ant-design-vue": "3.0.0-beta.8",
    "axios": "^0.25.0",
    "codemirror": "^5.65.1",
    "cropperjs": "^1.5.12",
    "crypto-js": "^4.1.1",
    "dayjs": "^1.10.7",
    "echarts": "^5.2.2",
    "intro.js": "^4.3.0",
    "lodash-es": "^4.17.21",
    "mockjs": "^1.1.0",
    "nprogress": "^0.2.0",
    "path-to-regexp": "^6.2.0",
    "pinia": "2.0.9",
    "print-js": "^1.6.0",
    "qrcode": "^1.5.0",
    "qs": "^6.10.3",
    "resize-observer-polyfill": "^1.5.1",
    "rollup": "2.66.1",
    "showdown": "^1.9.1",
    "sortablejs": "^1.14.0",
    "tinymce": "^5.10.2",
    "vditor": "^3.8.11",
    "vue": "^3.2.29",
    "vue-i18n": "^9.1.9",
    "vue-json-pretty": "^1.8.2",
    "vue-router": "^4.0.12",
    "vue-types": "^4.1.1",
    "xlsx": "^0.17.5"
  },
  "devDependencies": {
    "@commitlint/cli": "^16.1.0",
    "@commitlint/config-conventional": "^16.0.0",
    "@purge-icons/generated": "^0.7.0",
    "@types/codemirror": "^5.60.5",
    "@types/crypto-js": "^4.1.0",
    "@types/fs-extra": "^9.0.13",
    "@types/inquirer": "^8.1.3",
    "@types/intro.js": "^3.0.2",
    "@types/jest": "^27.4.0",
    "@types/lodash-es": "^4.17.5",
    "@types/mockjs": "^1.0.6",
    "@types/node": "^17.0.10",
    "@types/nprogress": "^0.2.0",
    "@types/qrcode": "^1.4.2",
    "@types/qs": "^6.9.7",
    "@types/showdown": "^1.9.4",
    "@types/sortablejs": "^1.10.7",
    "@typescript-eslint/eslint-plugin": "^5.10.0",
    "@typescript-eslint/parser": "^5.10.0",
    "@vitejs/plugin-legacy": "^1.6.4",
    "@vitejs/plugin-vue": "^2.1.0",
    "@vitejs/plugin-vue-jsx": "^1.3.3",
    "@vue/compiler-sfc": "3.2.29",
    "@vue/test-utils": "^2.0.0-rc.18",
    "autoprefixer": "^10.4.2",
    "cross-env": "^7.0.3",
    "dotenv": "^14.2.0",
    "eslint": "^8.7.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-define-config": "^1.2.3",
    "eslint-plugin-jest": "^25.7.0",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-vue": "^8.3.0",
    "esno": "^0.14.0",
    "fs-extra": "^10.0.0",
    "husky": "^7.0.4",
    "inquirer": "^8.2.0",
    "jest": "^27.4.7",
    "less": "^4.1.2",
    "lint-staged": "12.3.1",
    "npm-run-all": "^4.1.5",
    "postcss": "^8.4.5",
    "postcss-html": "^1.3.0",
    "postcss-less": "^6.0.0",
    "prettier": "^2.5.1",
    "rimraf": "^3.0.2",
    "rollup-plugin-visualizer": "^5.5.4",
    "stylelint": "^14.3.0",
    "stylelint-config-html": "^1.0.0",
    "stylelint-config-prettier": "^9.0.3",
    "stylelint-config-recommended": "^6.0.0",
    "stylelint-config-standard": "^24.0.0",
    "stylelint-order": "^5.0.0",
    "ts-jest": "^27.1.3",
    "ts-node": "^10.4.0",
    "typescript": "^4.5.5",
    "vite": "^2.8.0-beta.3",
	"vue-tsc": "^0.31.1",
    "vite-plugin-compression": "^0.4.0",
    "vite-plugin-html": "^2.1.2",
    "vite-plugin-vue-setup-extend": "^0.3.0",
    "vite-plugin-windicss": "^1.6.3",
    "vue-eslint-parser": "^8.2.0",
	"vite-plugin-mkcert": "^1.5.2",
    "vite-plugin-mock": "^2.9.6",
    "vite-plugin-purge-icons": "^0.7.0",
    "vite-plugin-style-import": "^1.4.1",
    "vite-plugin-theme": "^0.8.1",
	
	"vite-plugin-pwa": "^0.11.13",
"vite-plugin-svg-icons": "^1.1.0"
  },
  "resolutions": {
    "bin-wrapper": "npm:bin-wrapper-china"
  },

**Comment by flyrun9527** [comment]
我是新建vue3+vite项目 引入包报错

**Comment by anncwb** [comment]
尝试2.0.0
