### ISSUE TITLE
The packaged svg and the original svg rendering are inconsistent

### ISSUE THREAD

**Issue by sevenbluecity** [vbenjs/vite-plugin-svg-icons#54]
I have a svg file, like this:

`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
<path fill-rule="evenodd" clip-rule="evenodd" d="M11.709 9.80168C11.709 11.5302 13.1161 12.9373 14.8446 12.9373C16.5732 12.9373 17.9803 11.5302 17.9803 9.80168C17.9803 8.07313 16.5732 6.66602 14.8446 6.66602C13.1161 6.66602 11.709 8.07313 11.709 9.80168ZM13.1536 9.80373C13.1536 8.87052 13.9133 8.11271 14.8446 8.11271C15.776 8.11271 16.5357 8.87052 16.5357 9.80373C16.5357 10.7371 15.778 11.4948 14.8446 11.4948C13.9113 11.4948 13.1536 10.7371 13.1536 9.80373ZM15.7449 12.6515C16.9539 12.2684 17.8331 11.1354 17.8331 9.80168C17.8331 8.15444 16.4919 6.81324 14.8446 6.81324C14.5276 6.81324 14.2219 6.86292 13.9349 6.95491C14.2217 6.86307 14.5271 6.81348 14.8439 6.81348C16.4911 6.81348 17.8323 8.15468 17.8323 9.80191C17.8323 11.1353 16.9535 12.2682 15.7449 12.6515ZM14.2852 8.05255C13.5448 8.28968 13.0064 8.98444 13.0064 9.80373C13.0064 10.8184 13.83 11.642 14.8446 11.642C15.0388 11.642 15.2259 11.6118 15.4017 11.556C15.2257 11.612 15.0383 11.6422 14.8439 11.6422C13.8293 11.6422 13.0057 10.8186 13.0057 9.80397C13.0057 8.9844 13.5444 8.28946 14.2852 8.05255Z" fill="black" fill-opacity="0.75"/>
</svg>`

Open directly in the browser：
![image](https://user-images.githubusercontent.com/45512700/159857288-e51d7d12-5dcb-4bb0-940b-6356a2469f57.png)

But when I package with plugin：
`<symbol fill="none" viewBox="0 0 24 24" id="icon-picture">
<path fill-rule="evenodd" clip-rule="evenodd" d="M11.709 9.802a3.14 3.14 0 0 0 3.136 3.135 3.14 3.14 0 0 0 3.135-3.135 3.14 3.14 0 0 0-3.135-3.136 3.14 3.14 0 0 0-3.136 3.136Zm1.445.002c0-.933.76-1.691 1.69-1.691.932 0 1.692.758 1.692 1.69a1.692 1.692 0 0 1-3.382 0Zm2.59 2.848a2.995 2.995 0 0 0 2.09-2.85 2.993 2.993 0 1 0-.002 0 2.995 2.995 0 0 1-2.087 2.85Zm-1.459-4.6a1.839 1.839 0 1 0 0 0Z" fill="#000" fill-opacity=".75"></path>
</symbol>`

It is look like:
![image](https://user-images.githubusercontent.com/45512700/159858161-7ffdb465-8aa8-483d-979b-a1fd93552d7c.png)

**Comment by michaelhue** [comment]
The plugin uses [SVGO](https://github.com/svg/svgo) to compress the SVG files, which can lead to unexpected results like this.

You can provide a custom SVGO configuration using the `svgoOptions` key in the plugin config, or disable processing by SVGO completely:

```ts
import { createSvgIconsPlugin } from 'vite-plugin-svg-icons'
import path from 'path'

export default () => {
  return {
    plugins: [
      createSvgIconsPlugin({
        // ...other options...
        svgoOptions: false,
      }),
    ],
  }
}
```

This should solve the issue.

**Comment by sevenbluecity** [comment]
> The plugin uses [SVGO](https://github.com/svg/svgo) to compress the SVG files, which can lead to unexpected results like this.
> 
> You can provide a custom SVGO configuration using the `svgoOptions` key in the plugin config, or disable processing by SVGO completely:
> 
> ```ts
> import { createSvgIconsPlugin } from 'vite-plugin-svg-icons'
> import path from 'path'
> 
> export default () => {
>   return {
>     plugins: [
>       createSvgIconsPlugin({
>         // ...other options...
>         svgoOptions: false,
>       }),
>     ],
>   }
> }
> ```
> 
> This should solve the issue.

thanks, that is work for me.
